[package]
name = "gitevents_sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
eyre = "0.6.8"
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
tracing = { version = "0.1.37", features = ["log", "async-await"] }
